const fs = require("fs");
const html = fs.readFileSync("index.html", "utf8");
const js   = fs.readFileSync("app.js",     "utf8");
const p = (b, n) => console.log((b ? "✅ PASS" : "❌ FAIL"), n);

console.log("\n── index.html ─────────────────────────────────────────────");
p(html.includes('./public/PSA_Logo.png'),          "Logo → ./public/PSA_Logo.png");
p(html.includes(".analytics-hub"),                 "CSS .analytics-hub 3-col grid");
p(html.includes("repeat(3,1fr)"),                  "CSS 3-column template");
p(html.includes(".analytics-chart-card"),          "CSS .analytics-chart-card");
p(html.includes("hub-chart-canvas"),               "CSS .hub-chart-canvas");
p(html.includes(".matrix-constrained"),            "CSS .matrix-constrained scrollable");
p(html.includes("max-height:330px"),               "CSS max-height 330px for matrix");
p(html.includes("#errorToast"),                    "CSS #errorToast styles");
p(html.includes("errorToastText"),                 "HTML errorToastText span");
p(html.includes("id=\"errorToast\""),              "HTML errorToast element");
p(html.includes("grid-template-columns:1fr 1fr"), "Responsive 2-col at 1200px");

console.log("\n── app.js ─────────────────────────────────────────────────");
p(js.includes("psa_session"),                        "Auth: localStorage psa_session key");
p(js.includes("psa_user"),                           "Auth: localStorage psa_user key");
p(js.includes("checkAuthPersistence"),               "Auth: checkAuthPersistence() defined");
p(js.includes("showAppShell"),                       "Auth: showAppShell() helper");
p(js.includes('localStorage.setItem("psa_session"'),'Auth: setItem on login');
p(js.includes('localStorage.removeItem("psa_session")'),"Auth: removeItem on logout");
p(js.includes("function initChartsExecutive"),       "Charts: initChartsExecutive() defined");
p(js.includes('indexAxis: "y"'),                     "Charts: Horizontal Bar (indexAxis y)");
p(js.includes('id="chartHorizBar"'),                 "Charts: chartHorizBar canvas id");
p(js.includes('id="chartVertBar"'),                  "Charts: chartVertBar canvas id");
p(js.includes('id="chartDoughnut"'),                 "Charts: chartDoughnut canvas id");
p(js.includes("MONTH_ORDER.filter"),                 "Charts: Monthly volume from MONTH_ORDER");
p(js.includes("buildKpiHtml"),                       "Layout: buildKpiHtml() extracted");
p(js.includes("buildTableHtml"),                     "Layout: buildTableHtml() extracted");
p(js.includes("isExecutiveView"),                    "Layout: isExecutiveView conditional");
p(js.includes("analytics-hub"),                      "Layout: analytics-hub in HTML string");
p(js.includes("matrix-constrained"),                 "Layout: matrix-constrained table wrap");
p(js.includes("Data Matrix"),                        "Layout: Data Matrix table title");
p(js.includes("Department Layout"),                  "Layout: department view comment");
p(js.includes("Analytics Hub"),                      "Layout: exec view comment");
p(js.includes('setAttribute("max"'),                 "Validation: max attr set on date input");
p(js.includes('toISOString().split("T")[0]'),        "Validation: today as max date");
p(js.includes("parsedYear < 2020"),                  "Validation: pre-2020 check");
p(js.includes("showErrorToast"),                     "Validation: showErrorToast() called");
p(js.includes("function showErrorToast"),            "Validation: showErrorToast() defined");
p(js.includes("errorToastText"),                     "Validation: errorToastText element");
p(js.includes("horizBar"),                           "Reactive: horizBar in updateCharts");
p(js.includes("vertBar"),                            "Reactive: vertBar in updateCharts");
p(js.includes('doughnut.update("active")'),          "Reactive: doughnut.update()");
p(js.includes("darkTooltip"),                        "Charts: shared darkTooltip config");
p(js.includes("DEPT_COLORS"),                        "Charts: DEPT_COLORS solid high-contrast");

const lineCount = js.split("\n").length;
const byteCount = fs.statSync("app.js").size;
console.log(`\napp.js: ${lineCount} lines, ${byteCount} bytes`);
